#!/bin/bash

# Define colors using tput
green=$(tput setaf 2)
red=$(tput setaf 1)
reset=$(tput sgr0)

# Loop through all subdirectories of the current directory
for dir in */ ; do
  # Check if the directory contains a .git folder
  if [ -d "$dir/.git" ]; then
    echo "${green}$dir is a Git repository${reset}"
  else
    echo "${red}$dir is not a Git repository${reset}"
  fi
done

